name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' 

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Cypress binary
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/Cypress
        key: cypress-${{ runner.os }}-${{ hashFiles('**/*.json') }}
        restore-keys: |
          cypress-${{ runner.os }}-
          cypress-latest

    - name: Install dependencies
      run: npm install

    - name: Install ts-node
      run: npm install --save-dev ts-node

    - name: Run Cypress tests
      run: |
        # Check if Cypress binary is already installed in cache
        if [ -d ~/.cache/Cypress ]; then
          npx cypress run
        else
          npx cypress install
          npx cypress run
        fi
      working-directory: .
