name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' 

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Cypress binary
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/Cypress
        key: cypress-${{ runner.os }}-${{ hashFiles('**/*.json') }}
        restore-keys: |
          cypress-${{ runner.os }}-
          cypress-latest

    - name: Install dependencies
      run: npm install

    - name: Install Percy CLI
      run: npm install -D @percy/cli

    - name: Set Percy credentials (securely)
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      run: |
        percy config set --api --token $PERCY_TOKEN  # Store token in Percy's config

    - name: Run Cypress tests
      run: |
        # Check if Cypress binary is already installed in cache
        if [ -d ~/.cache/Cypress ]; then
          npx cypress run
        else
          npx cypress install
          npx cypress run
        fi
      working-directory: .

    - name: Run Percy snapshot validation
      run: |
        npx percy run \
          --spec cypress/e2e/**/*.ts \  # Adjust this path based on your test file location
          --percy-config=.percy.config.js  # Specify your custom Percy config if needed
