name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' 

    - name: Install dependencies
      run: npm install

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Cypress tests
      run: npx cypress run
